[package]
name = "drocsid"
version = "0.1.0"
authors = ["williamt"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.7.3"
tokio = {version="0.2.16", features=["full"]}
rand = "0.7.3"